# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
